"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef, useState } from "react";
import { Play, X } from "lucide-react";
import { localVideos } from "@/data/localVideos";
import { videoLinks } from "@/data/videoLinks";

const durationLabel = seconds => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
const brands = ["All projects", ...new Set(localVideos.map(v => v.brand))];
export default function VideoPortfolio() {
  const [brand, setBrand] = useState("All projects");
  const [active, setActive] = useState(null);
  const closeButton = useRef(null);
  const origin = useRef(null);
  const featured = localVideos.find(v => v.brand === "Cám Ơn") || localVideos[0];
  const projects = localVideos.filter(v => brand === "All projects" || v.brand === brand);
  useEffect(() => {
    if (!active) return;
    const oldOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    closeButton.current?.focus();
    const handleKey = e => { if (e.key === "Escape") setActive(null); };
    window.addEventListener("keydown", handleKey);
    return () => { document.body.style.overflow = oldOverflow; window.removeEventListener("keydown", handleKey); origin.current?.focus(); };
  }, [active]);
  const open = (v, e) => { origin.current = e.currentTarget; setActive(v); };
  return <div className="mx-auto max-w-[1400px] px-5 pt-14 md:px-10 md:pt-20">
    <div className="grid gap-8 lg:grid-cols-[1.5fr_1fr] lg:items-end"><div><p className="section-kicker text-[#a8c7ff]">Campaign films / Food, feeling & motion</p><h3 className="mt-5 text-[clamp(2.5rem,5.5vw,5rem)] font-bold leading-[.98] tracking-[-.055em]">Ideas that move.<br /><span className="text-[#a8c7ff]">Stories that stay.</span></h3></div><div><p className="max-w-md text-sm leading-7 text-white/60 md:text-base">Food stories, café moments, and seasonal campaigns. Explore the films for Senglao Café, Kaogee, and Cám Ơn, and play each project directly here.</p><div className="mt-6 flex gap-8 border-t border-white/15 pt-5"><div><strong className="text-2xl">{String(localVideos.length).padStart(2,"0")}</strong><p className="mt-1 text-xs text-white/50">Campaign films</p></div><div><strong className="text-2xl">HD</strong><p className="mt-1 text-xs text-white/50">Original video files</p></div></div></div></div>
    {featured && <div className="mt-12 overflow-hidden rounded-2xl border border-white/15 bg-[#101318] lg:grid lg:grid-cols-[1fr_1fr]"><button onClick={e => open(featured,e)} aria-label={`Play featured film: ${featured.title}`} className="group relative flex h-[420px] items-center justify-center overflow-hidden bg-black md:h-[520px]"><img src={featured.poster} alt={featured.title} className="h-full w-full object-contain" /><span className="absolute grid h-20 w-20 place-items-center rounded-full border border-white/40 bg-black/50 backdrop-blur transition group-hover:scale-110"><Play size={27} fill="currentColor" /></span><span className="absolute bottom-4 right-4 rounded-full bg-black/75 px-3 py-1 font-mono text-xs">{durationLabel(featured.duration)}</span></button><div className="flex flex-col justify-center p-7 md:p-10"><p className="section-kicker text-[#e6bd79]">Featured campaign / {featured.brand}</p><h4 className="mt-5 text-3xl font-semibold tracking-tight md:text-4xl">{featured.title}</h4><p className="mt-4 text-sm leading-7 text-white/55">A seasonal brand moment, brought to life through moving images. Watch the complete film with sound.</p><button onClick={e => open(featured,e)} className="mt-7 inline-flex w-fit items-center gap-3 rounded-full bg-[#a8c7ff] px-6 py-3 text-sm font-semibold text-[#081323]"><Play size={15} fill="currentColor" /> Watch film</button></div></div>}
    <div className="mt-12 flex flex-col justify-between gap-5 border-b border-white/15 pb-6 md:flex-row md:items-center"><div className="flex flex-wrap gap-2" role="group" aria-label="Filter video projects">{brands.map(b => <button key={b} aria-pressed={brand === b} onClick={() => setBrand(b)} className={`rounded-full border px-5 py-2.5 text-xs font-semibold transition ${brand === b ? "border-[#a8c7ff] bg-[#a8c7ff] text-[#081323]" : "border-white/20 text-white/60 hover:border-white/60 hover:text-white"}`}>{b}<span className="ml-2 opacity-60">{localVideos.filter(v => b === "All projects" || v.brand === b).length}</span></button>)}</div><p className="font-mono text-[10px] uppercase tracking-[.15em] text-white/40">Select a film to watch</p></div>
    <div className="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{projects.map(v => <article key={v.id} className="overflow-hidden rounded-2xl border border-white/15 bg-[#101318]"><button onClick={e => open(v,e)} aria-label={`Play ${v.title}`} className="group relative flex aspect-[4/5] w-full items-center justify-center overflow-hidden bg-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#a8c7ff]"><img src={v.poster} alt={v.title} loading="lazy" decoding="async" className="h-full w-full object-contain" /><span className="absolute grid h-14 w-14 place-items-center rounded-full border border-white/40 bg-black/55 backdrop-blur transition group-hover:scale-110 group-hover:bg-[#a8c7ff] group-hover:text-black"><Play size={21} fill="currentColor" /></span><span className="absolute bottom-3 right-3 rounded-full bg-black/75 px-3 py-1 font-mono text-[11px]">{durationLabel(v.duration)}</span></button><div className="p-5"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[#a8c7ff]">{v.brand} / {v.width < v.height ? "Vertical film" : "Campaign video"}</p><h4 className="mt-3 text-xl font-semibold tracking-tight">{v.title}</h4><button onClick={e => open(v,e)} className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-[#a8c7ff]"><Play size={12} /> Watch film</button></div></article>)}</div>
    <section id="video-links" className="mt-16 border-t border-white/15 pt-10" aria-labelledby="video-links-heading">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="section-kicker text-[#a8c7ff]">More video work / Social portfolio</p><h4 id="video-links-heading" className="mt-4 text-3xl font-semibold tracking-tight">Watch on Facebook.</h4><p className="mt-3 text-sm text-white/55">Explore the AI stories, reels, and event film in the linked collection.</p></div><span className="font-mono text-xs text-white/40">{videoLinks.length} video links</span></div>
      <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{videoLinks.map(v => <a key={v.id} href={v.url} target="_blank" rel="noopener noreferrer" aria-label={`Watch ${v.title} on Facebook (opens in a new tab)`} className="group flex items-center gap-4 rounded-xl border border-white/15 bg-[#101318] p-5 transition hover:border-[#a8c7ff]/70 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#a8c7ff]"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#a8c7ff]/10 text-[#a8c7ff]"><Play size={16} fill="currentColor" /></span><span className="min-w-0 flex-1"><span className="block font-mono text-[9px] uppercase tracking-[.15em] text-white/40">{v.category === "event" ? "Event film" : "AI stories & reels"}</span><span className="mt-2 block text-sm font-semibold">{v.title}</span><span className="mt-2 block text-xs text-[#a8c7ff]">Watch on Facebook ↗</span></span></a>)}</div>
    </section>
    {active && <div role="dialog" aria-modal="true" aria-label={active.title} onClick={() => setActive(null)} className="fixed inset-0 z-[100] flex flex-col items-center justify-center bg-black/95 p-4 backdrop-blur-lg"><button ref={closeButton} onClick={() => setActive(null)} aria-label="Close video" className="absolute right-5 top-5 rounded-full border border-white/30 bg-black p-3"><X size={20} /></button><video key={active.src} src={active.src} poster={active.poster} controls autoPlay playsInline onClick={e => e.stopPropagation()} aria-label={active.title} className="max-h-[75svh] w-auto max-w-[95vw] bg-black" /><p className="mt-5 text-center text-sm text-white/70">{active.brand} / {active.title}</p></div>}
  </div>;
}


